### ISSUE TITLE
[GAME] [Linux/Steam Deck] Crashes

### ISSUE THREAD

**Issue by MartinX3** [entropy-zero/source-sdk-2013#181]
### Describe the bug
The game crashes every day I play with the steam deck branch.
Luckily the crashes were always random, until now.
I've got a save game which always crashes and I hope it helps to debug the problem.
The game just freezes and then after a while I'm on my linux desktop.

### Steps to reproduce
1. Save game [save.zip](https://github.com/entropy-zero/source-sdk-2013/files/10528362/save.zip)
2. Load
3. Crash

### Expected behavior
A crash free experience.

---

### Additional context
I use Arch Linux.
Nvidia Optimus (Game runs on the GTX 940MX Laptop GPU)
I use the steam deck branch.

**Comment by Blixibon** [comment]
The area that this save is located in is consistent with a long-running crash some players have been experiencing since launch. However, I wasn't able to recreate this crash on my Ubuntu machine running on E:Z2's 1.4.2 update.

If you are still affected by this issue, could you see if you could reproduce this on the `release-1.4` branch? (for clarity, `release-1.4` is the successor to `deck-testing` and should work in the same way)

**Comment by MartinX3** [comment]
Thank you, I think 1.4 fixed the issue. :)
