### ISSUE TITLE
[NPCs] husk/assassin crash

### ISSUE THREAD

**Issue by breakdowngamesYT** [entropy-zero/source-sdk-2013#224]
### Bug
whenever a husk or assassin model is loaded on a map it crashes the game

### Steps to reproduce
1. set beta branch to release-1.6/upcoming
2. load a map featuring either npc/spawn either npc via the console

### Expected behavior
you should be able to spawn the npc/load a map featuring them with no issues

**Comment by 1upD** [comment]
This is not a reproducible bug. Can you give us a little more detail about what happened? Are you sure that the update installed correctly, and did you try verifying your game cache?

**Comment by breakdowngamesYT** [comment]
i fixed it. it was a workshop mod changing the combines animations

**Comment by 1upD** [comment]
For future reference, when encountering a problem like this, please use the Steam forums, the Steam comments on the troubleshooting guide, or our Discord server before submitting an Issue on GitHub. GitHub issues are for reproducible bugs directly related to the game's code. Bugs caused by workshop addons or normal issues with the game installation are not suitable for GitHub issues.

**Comment by breakdowngamesYT** [comment]
understood
